# Generated by Django 2.1.5 on 2019-01-15 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseDeDados',
            fields=[
                ('driver', models.CharField(choices=[('sql server', 'SQL Server'), ('microsoft odbc for oracle', 'Microsoft ODBC for Oracle'), ('oracle in oraclient11g_home1', 'Oracle in OraClient11g_home1')], max_length=200, verbose_name='Driver da Base ')),
                ('server_instancia', models.CharField(blank=True, max_length=50, null=True, verbose_name='Servidor \\ Instância ')),
                ('alias', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Nome da Base ')),
                ('usuario', models.CharField(max_length=100, verbose_name='Usuário ')),
                ('password', models.CharField(max_length=50, verbose_name='Senha ')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação ')),
                ('data_modificacao', models.DateTimeField(auto_now=True, verbose_name='Data Modificação ')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nome_cliente', models.CharField(max_length=250, verbose_name='Cliente ')),
                ('chave_cliente', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Sigla do Cliente')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação ')),
                ('data_modificacao', models.DateTimeField(auto_now=True, verbose_name='Data Modificação ')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('chave_consulta', models.AutoField(primary_key=True, serialize=False)),
                ('nome_consulta', models.CharField(max_length=250, unique=True, verbose_name='Nome da Consulta ')),
                ('descricao_consulta', models.CharField(max_length=500, verbose_name='Descrição ')),
                ('origem_consulta', models.CharField(choices=[('rtc', 'RTC'), ('sac', 'SAC'), ('sccd', 'SCCD'), ('interno', 'INTERNO')], max_length=20, verbose_name='Origem da Conulta ')),
                ('descricao_origem', models.TextField(verbose_name='Descição da Origem ')),
                ('consulta_ativa', models.BooleanField(verbose_name='Consulta Ativa ')),
                ('data_inicio', models.DateTimeField(verbose_name='Data Inicio das Consultas ')),
                ('data_fim', models.DateTimeField(verbose_name='Data Fim das Consultas ')),
                ('max_consulta', models.PositiveIntegerField(verbose_name='Só Rodar Consulta Com Valor Menor Que ')),
                ('sql_qtd_consulta', models.TextField(verbose_name='SQL Que Retorna a Quantidade de Valores ')),
                ('sql_valores_consulta', models.TextField(verbose_name='SQL Que Retorna Os Valores ')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação ')),
                ('data_modificacao', models.DateTimeField(auto_now=True, verbose_name='Data Modificação ')),
                ('nome_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SiteMonitoramentoMSAJ.BaseDeDados', verbose_name='Base ')),
                ('nome_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SiteMonitoramentoMSAJ.Cliente', verbose_name='Cliente ')),
            ],
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('nome_modulo', models.CharField(max_length=250, verbose_name='Modulo ')),
                ('descricao_modulo', models.CharField(max_length=250, primary_key=True, serialize=False, verbose_name='Local do Sistema ')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação ')),
                ('data_modificacao', models.DateTimeField(auto_now=True, verbose_name='Data Modificação ')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoConsulta',
            fields=[
                ('chave_resultado', models.AutoField(primary_key=True, serialize=False, verbose_name='ID do Resultado ')),
                ('nuseqexecucao', models.IntegerField(default=0, verbose_name='Sequência de Execução ')),
                ('dtexecucao', models.DateTimeField(verbose_name='Data da Execução')),
                ('deversao', models.CharField(max_length=150, verbose_name='Versão do Cliente em Produção')),
                ('qtdvalores', models.IntegerField(verbose_name='Quantidade Encontrada ')),
                ('valores_consulta', models.TextField(null=True, verbose_name='Resultados ')),
                ('observacao', models.TextField(null=True, verbose_name='Observação ')),
                ('consulta_chave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SiteMonitoramentoMSAJ.Consulta', verbose_name='ID da Consulta')),
            ],
        ),
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('nome_sistema', models.CharField(max_length=250, verbose_name='Sistema ')),
                ('sigla_sistema', models.CharField(max_length=10, verbose_name='Sigla do Sistema ')),
                ('chave_sistema', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ID do Sistema ')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação ')),
                ('data_modificacao', models.DateTimeField(auto_now=True, verbose_name='Data Modificação ')),
            ],
        ),
        migrations.AddField(
            model_name='modulo',
            name='id_sistema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SiteMonitoramentoMSAJ.Sistema', verbose_name='Sistema'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='nome_modulo_consulta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SiteMonitoramentoMSAJ.Modulo', verbose_name='Local do Sistema '),
        ),
        migrations.AddField(
            model_name='consulta',
            name='nome_sistema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SiteMonitoramentoMSAJ.Sistema', verbose_name='Sistema '),
        ),
        migrations.AddField(
            model_name='basededados',
            name='id_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SiteMonitoramentoMSAJ.Cliente', verbose_name='Cliente '),
        ),
        migrations.AddField(
            model_name='basededados',
            name='id_sistema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SiteMonitoramentoMSAJ.Sistema', verbose_name='Sistema '),
        ),
    ]
